# Generated by Django 5.0.4 on 2024-06-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0004_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elo_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='elo_rating',
            field=models.IntegerField(default=1500),
        ),
    ]
