# Generated by Django 5.0.4 on 2024-07-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0010_remove_userprofile_elo_rating_elorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_code',
            field=models.CharField(default=12, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
