# Generated by Django 5.0.4 on 2024-11-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0012_game_blocker_move_count_game_last_move_blocker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='blocker_move_count',
            new_name='blue_blocker_count',
        ),
        migrations.AddField(
            model_name='game',
            name='move_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='red_blocker_count',
            field=models.IntegerField(default=0),
        ),
    ]
