# Generated by Django 5.0.4 on 2024-12-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0013_rename_blocker_move_count_game_blue_blocker_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#121212', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='board_color',
            field=models.CharField(default='#edd8a8', max_length=7),
        ),
    ]
