# Generated by Django 5.0.4 on 2024-12-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0014_userprofile_background_color_userprofile_board_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#d3d2c0', max_length=7),
        ),
    ]
