# Generated by Django 5.0.4 on 2024-12-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0016_update_default_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='move_count',
            new_name='moves_made',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_move_blocker',
        ),
        migrations.AddField(
            model_name='game',
            name='blue_power',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='game',
            name='red_power',
            field=models.IntegerField(default=2),
        ),
    ]
