# Generated by Django 5.0.4 on 2025-01-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0017_rename_move_count_game_moves_made_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='blue_power',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_power',
            field=models.IntegerField(default=0),
        ),
    ]
