# Generated by Django 5.0.4 on 2025-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0018_alter_game_blue_power_alter_game_red_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_size',
            field=models.IntegerField(choices=[(3, '3x3x3'), (4, '4x4x4')], default=3),
        ),
    ]
