# Generated by Django 5.0.4 on 2025-11-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0019_game_board_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elorating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='elorating',
            name='board_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterUniqueTogether(
            name='elorating',
            unique_together={('user_profile', 'game_type', 'board_size')},
        ),
    ]
