# Generated by Django 5.0.4 on 2025-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactictoe', '0020_add_board_size_to_elorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='initial_board_state',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.JSONField(default=list),
        ),
    ]
