# Generated by Django 5.0.4 on 2024-06-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoefrontend', '0005_game_elo_change_alter_userprofile_elo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='elo_change',
            field=models.IntegerField(default=None),
        ),
    ]
