# Generated by Django 5.0.4 on 2024-06-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoefrontend', '0006_alter_game_elo_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='elo_change',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
