# Generated by Django 5.0.4 on 2024-07-21 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoefrontend', '0008_game_last_move_time_game_player_one_time_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('rapid', 'rapid'), ('blitz', 'blitz')], default='rapid', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='player_one_time_left',
            field=models.DurationField(default=datetime.timedelta(seconds=180)),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two_time_left',
            field=models.DurationField(default=datetime.timedelta(seconds=180)),
        ),
    ]
