# Generated by Django 5.0.4 on 2024-07-22 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoefrontend', '0009_game_game_type_alter_game_player_one_time_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='elo_rating',
        ),
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('rapid', 'rapid'), ('blitz', 'blitz')], max_length=20)),
                ('rating', models.IntegerField(default=1500)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to='tictactoefrontend.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'game_type')},
            },
        ),
    ]
